### ISSUE TITLE
EXPRESS WITH SEQUELIZE - add relations options

### ISSUE THREAD

**Issue by AlixBa** [JeyDotC/articles#1]
First of all, thank you for your singleton, it has been very helpfull to me.
However I needed to add some options to my relations, as shown here, for instance : `Project.hasOne(User, { foreignKey: 'initiator_id' })`.

To achieve that, I modified your code and the Model structure.

```
// in Project.js
"relations": {
    "hasOne": {
    "model": "User",
    "options": {
        "foreignKey": "initiator_id"
        }
    }
}

// in the singleton.js
for (var name in relationships) {
    var relations = relationships[name];
    for (var relation in relations) {
        var related = relations[relation];
        models[name][relation](models[related.model], related.options);
    }
}
```

This is just to make an how to if somebody needs that :)

**Comment by JeyDotC** [comment]
I have been trying to create a Jekill page for the articles in order to allow comments, but it doesn't work :( so, for now, posting comments in the issues is ok :)

**Comment by AlixBa** [comment]
Ok, that was bad. I did not think about multiple relations with the same name (for instance, two "hasMany"). With the previous code, it leads to a major problem :^D.

This is what I'm using instead (not proud of the 3 `for`)

```
// singleton
for (var model in relationships) {
    var relations = relationships[model];
    for (var relation in relations) {
        var related = relations[relation];
        for (var rel_model in related) {
            var rel_opt = related[rel_model];
            models[model][relation](models[rel_model], rel_opt || {});
        }
    }
}

// model
"relations": {
    "belongsTo": {
        "teacher": {
            "foreignKeyConstraint": true
        },
        "reservation": {
            "foreignKeyConstraint": true
        }
    }
},
```

If you have a easier solution, I'll take it !
